# Generated by Django 4.0.6 on 2022-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast2',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('starttime', models.DateTimeField(db_column='StartTime')),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('maxtension', models.IntegerField(blank=True, db_column='MaxTension', null=True)),
                ('maxpayout', models.IntegerField(blank=True, db_column='MaxPayout', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cast2',
                'db_table': 'Cast2',
                'managed': False,
            },
        ),
    ]
