# Generated by Django 4.0.6 on 2022-08-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0002_cast2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast2',
        ),
    ]
