# Generated by Django 4.0.6 on 2022-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0003_delete_cast2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'managed': True, 'verbose_name_plural': 'Cast'},
        ),
    ]
