# Generated by Django 4.0.6 on 2022-08-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0004_alter_cast_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibration',
            options={'managed': True, 'verbose_name_plural': 'Calibration'},
        ),
        migrations.AlterModelOptions(
            name='calibrationmeta',
            options={'managed': True, 'verbose_name_plural': 'CalibrationMeta'},
        ),
        migrations.AlterModelOptions(
            name='cutbacksretermination',
            options={'managed': True, 'verbose_name_plural': 'CutbacksRetermination'},
        ),
        migrations.AlterModelOptions(
            name='deploymenttype',
            options={'managed': True, 'verbose_name_plural': 'DeploymentType'},
        ),
        migrations.AlterModelOptions(
            name='drum',
            options={'managed': True, 'verbose_name_plural': 'Drum'},
        ),
        migrations.AlterModelOptions(
            name='dynomometer',
            options={'managed': True, 'verbose_name_plural': 'Dynomometer'},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'managed': True, 'verbose_name_plural': 'Frame'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='lubrication',
            options={'managed': True, 'verbose_name_plural': 'Lubrication'},
        ),
        migrations.AlterModelOptions(
            name='safeworkinglimit',
            options={'managed': True, 'verbose_name_plural': 'SafeWorkingLimit'},
        ),
        migrations.AlterModelOptions(
            name='termination',
            options={'managed': True, 'verbose_name_plural': 'Termination'},
        ),
        migrations.AlterModelOptions(
            name='winch',
            options={'managed': True, 'verbose_name_plural': 'Winch'},
        ),
        migrations.AlterModelOptions(
            name='winchoperator',
            options={'managed': True, 'verbose_name_plural': 'WinchOperator'},
        ),
        migrations.AlterModelOptions(
            name='wire',
            options={'managed': True, 'verbose_name_plural': 'Wire'},
        ),
        migrations.AlterModelOptions(
            name='wiredrum',
            options={'managed': True, 'verbose_name_plural': 'WireDrum'},
        ),
        migrations.AlterModelOptions(
            name='wireropedata',
            options={'managed': True, 'verbose_name_plural': 'WireRopeData'},
        ),
        migrations.AlterModelOptions(
            name='wiretermination',
            options={'managed': True, 'verbose_name_plural': 'WireTermination'},
        ),
        migrations.AddField(
            model_name='cast',
            name='deploymenttypeid',
            field=models.ForeignKey(db_column='DeploymentTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.deploymenttype'),
        ),
        migrations.AddField(
            model_name='cast',
            name='endtime',
            field=models.DateField(blank=True, db_column='EndTime', null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='operatorid',
            field=models.ForeignKey(db_column='OperatorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winchoperator'),
        ),
        migrations.AddField(
            model_name='cast',
            name='starttime',
            field=models.DateField(db_column='StartTime', null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='winchid',
            field=models.ForeignKey(db_column='WinchId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winch'),
        ),
        migrations.AddField(
            model_name='cast',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='startdate',
            field=models.DateField(db_column='StartDate', null=True),
        ),
    ]
