# Generated by Django 4.0.6 on 2022-08-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0005_alter_calibration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='calibrationid',
            field=models.ForeignKey(blank=True, db_column='CalibrationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.calibrationmeta'),
        ),
        migrations.AddField(
            model_name='calibrationmeta',
            name='dynomometerid',
            field=models.ForeignKey(blank=True, db_column='DynomometerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.dynomometer'),
        ),
        migrations.AddField(
            model_name='calibrationmeta',
            name='frameid',
            field=models.ForeignKey(blank=True, db_column='FrameId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.frame'),
        ),
        migrations.AddField(
            model_name='calibrationmeta',
            name='operatorid',
            field=models.ForeignKey(blank=True, db_column='OperatorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winchoperator'),
        ),
        migrations.AddField(
            model_name='calibrationmeta',
            name='winchid',
            field=models.ForeignKey(blank=True, db_column='WinchId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winch'),
        ),
        migrations.AddField(
            model_name='calibrationmeta',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AddField(
            model_name='cutbacksretermination',
            name='terminationid',
            field=models.ForeignKey(blank=True, db_column='TerminationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.termination'),
        ),
        migrations.AddField(
            model_name='cutbacksretermination',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AddField(
            model_name='drum',
            name='locationid',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.location'),
        ),
        migrations.AddField(
            model_name='lubrication',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AddField(
            model_name='safeworkinglimit',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AddField(
            model_name='winch',
            name='locationid',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.location'),
        ),
        migrations.AddField(
            model_name='winchoperator',
            name='username',
            field=models.TextField(blank=True, db_column='UserName', null=True),
        ),
        migrations.AddField(
            model_name='wire',
            name='wireropeid',
            field=models.ForeignKey(blank=True, db_column='WireRopeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wireropedata'),
        ),
        migrations.AddField(
            model_name='wiredrum',
            name='drumid',
            field=models.ForeignKey(blank=True, db_column='DrumId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.drum'),
        ),
        migrations.AddField(
            model_name='wiredrum',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AddField(
            model_name='wiretermination',
            name='terminationid',
            field=models.ForeignKey(blank=True, db_column='TerminationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.termination'),
        ),
        migrations.AddField(
            model_name='wiretermination',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.wire'),
        ),
        migrations.AlterField(
            model_name='winchoperator',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
