# Generated by Django 4.0.6 on 2022-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0006_calibration_calibrationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='endtime',
            field=models.TimeField(blank=True, db_column='EndTime', null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='starttime',
            field=models.TimeField(db_column='StartTime', null=True),
        ),
    ]
