# Generated by Django 4.0.6 on 2022-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0007_alter_cast_endtime_alter_cast_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='starttime',
        ),
        migrations.AlterField(
            model_name='cast',
            name='enddate',
            field=models.DateTimeField(blank=True, db_column='EndDate', null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='startdate',
            field=models.DateTimeField(db_column='StartDate', null=True),
        ),
    ]
