# Generated by Django 4.0.6 on 2022-08-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0008_remove_cast_endtime_remove_cast_starttime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutbacksretermination',
            new_name='Cutbackretermination',
        ),
        migrations.AlterModelOptions(
            name='cutbackretermination',
            options={'managed': True, 'verbose_name_plural': 'CutbackRetermination'},
        ),
        migrations.AlterModelTable(
            name='cutbackretermination',
            table='CutbackRetermination',
        ),
    ]
