# Generated by Django 4.0.6 on 2022-08-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0009_rename_cutbacksretermination_cutbackretermination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winch',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
    ]
