# Generated by Django 4.0.6 on 2022-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0010_winch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenttype',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
    ]
