# Generated by Django 4.0.6 on 2022-08-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0011_deploymenttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='operatorid',
        ),
        migrations.AddField(
            model_name='cast',
            name='endoperatorid',
            field=models.ForeignKey(db_column='EndOperatorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='endoperatorid', to='wwdb.winchoperator'),
        ),
        migrations.AddField(
            model_name='cast',
            name='startoperatorid',
            field=models.ForeignKey(db_column='StartOperatorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='startoperatorid', to='wwdb.winchoperator'),
        ),
    ]
