# Generated by Django 4.0.6 on 2022-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0012_remove_cast_operatorid_cast_endoperatorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termination',
            old_name='terminationid',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dynomometer',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
        migrations.AddField(
            model_name='wireropedata',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
    ]
