# Generated by Django 4.0.6 on 2022-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0013_rename_terminationid_termination_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenttype',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', null=True),
        ),
    ]
