# Generated by Django 4.0.6 on 2022-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0014_deploymenttype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wire',
            name='status',
            field=models.BooleanField(blank=True, db_column='Status', null=True),
        ),
    ]
