# Generated by Django 4.0.6 on 2022-09-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0015_alter_wire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wire',
            name='winchid',
            field=models.ForeignKey(blank=True, db_column='WinchId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winch'),
        ),
    ]
