# Generated by Django 4.0.3 on 2022-09-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwdb', '0016_wire_winchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinchDrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('drumid', models.ForeignKey(blank=True, db_column='DrumId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.drum')),
                ('enteredby', models.ForeignKey(blank=True, db_column='EnteredBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WinchDrum',
                'db_table': 'WinchDrum',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='winch',
            name='active',
            field=models.BooleanField(db_column='Active', default=True),
        ),
        migrations.AddField(
            model_name='winch',
            name='drum',
            field=models.ManyToManyField(through='wwdb.WinchDrum', to='wwdb.drum'),
        ),
        migrations.AddField(
            model_name='winchdrum',
            name='winchid',
            field=models.ForeignKey(blank=True, db_column='WinchId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winch'),
        ),
    ]
