# Generated by Django 4.0.3 on 2022-09-20 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwdb', '0017_winchdrum_winch_active_winch_drum_winchdrum_winchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorOfSafety',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('factorofsafety', models.FloatField(db_column='FactorofSafety', default=5.0)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('enteredby', models.ForeignKey(blank=True, db_column='EnteredBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SafeWorkingLimit',
                'db_table': 'FactorOfSafety',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='winch',
            name='drum',
        ),
        migrations.AddField(
            model_name='winch',
            name='drums',
            field=models.ManyToManyField(related_name='winches', through='wwdb.WinchDrum', to='wwdb.drum'),
        ),
        migrations.AddField(
            model_name='wire',
            name='drums',
            field=models.ManyToManyField(related_name='loaded_wires', through='wwdb.Wiredrum', to='wwdb.drum'),
        ),
        migrations.DeleteModel(
            name='Safeworkinglimit',
        ),
        migrations.AddField(
            model_name='factorofsafety',
            name='wireid',
            field=models.ForeignKey(blank=True, db_column='WireId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factorofsafety', to='wwdb.wire'),
        ),
    ]
