# Generated by Django 4.0.6 on 2022-09-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwdb', '0018_factorofsafety_remove_winch_drum_winch_drums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrumLocation',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'verbose_name_plural': 'DrumLocation',
                'db_table': 'DrumLocation',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='factorofsafety',
            options={'managed': True, 'verbose_name_plural': 'FactorOfSafety'},
        ),
        migrations.RemoveField(
            model_name='drum',
            name='locationid',
        ),
        migrations.RemoveField(
            model_name='winch',
            name='drums',
        ),
        migrations.RemoveField(
            model_name='winch',
            name='locationid',
        ),
        migrations.DeleteModel(
            name='WinchDrum',
        ),
        migrations.AddField(
            model_name='drumlocation',
            name='drumid',
            field=models.ForeignKey(blank=True, db_column='DrumId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.drum'),
        ),
        migrations.AddField(
            model_name='drumlocation',
            name='enteredby',
            field=models.ForeignKey(blank=True, db_column='EnteredBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drumlocation',
            name='locationid',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.location'),
        ),
    ]
