# Generated by Django 4.0.6 on 2022-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0020_breaktest_remove_wiretermination_terminationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumlocation',
            name='winchid',
            field=models.ForeignKey(blank=True, db_column='WinchId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.winch'),
        ),
        migrations.AddField(
            model_name='winch',
            name='drums',
            field=models.ManyToManyField(related_name='winches', through='wwdb.DrumLocation', to='wwdb.drum'),
        ),
    ]
