# Generated by Django 4.0.6 on 2022-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0021_drumlocation_winchid_winch_drums'),
    ]

    operations = [
        migrations.AddField(
            model_name='drum',
            name='wire',
            field=models.ManyToManyField(related_name='wires_drums', through='wwdb.Wiredrum', to='wwdb.wire'),
        ),
    ]
