# Generated by Django 4.1.3 on 2022-12-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0022_drum_wire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drum",
            name="wire",
        ),
        migrations.AlterField(
            model_name="cast",
            name="startoperatorid",
            field=models.ForeignKey(
                db_column="StartOperatorId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="startoperatorid",
                to="wwdb.winchoperator",
                verbose_name="Start operator",
            ),
        ),
    ]
