# Generated by Django 4.1.3 on 2022-12-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0024_remove_factorofsafety_wireid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factorofsafety",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="factorofsafety",
            name="enteredby",
        ),
        migrations.RemoveField(
            model_name="factorofsafety",
            name="notes",
        ),
    ]
