# Generated by Django 4.1.3 on 2022-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0026_cast_factorofsafety_cast_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="factorofsafety",
            field=models.FloatField(
                db_column="FactorofSafety", verbose_name="Factor of safety"
            ),
        ),
    ]
