# Generated by Django 4.1.3 on 2022-12-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0027_alter_cast_factorofsafety"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cast",
            name="status",
        ),
        migrations.AddField(
            model_name="cast",
            name="flagforreview",
            field=models.BooleanField(
                blank=True,
                db_column="Flagforreview",
                null=True,
                verbose_name="Flag for review",
            ),
        ),
    ]
