# Generated by Django 4.1.3 on 2022-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0028_remove_cast_status_cast_flagforreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="factorofsafety",
            field=models.FloatField(
                blank=True, db_column="FactorofSafety", verbose_name="Factor of safety"
            ),
        ),
    ]
