# Generated by Django 4.1.3 on 2022-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0029_alter_cast_factorofsafety"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="factorofsafety",
            field=models.FloatField(
                blank=True,
                db_column="FactorofSafety",
                null=True,
                verbose_name="Factor of safety",
            ),
        ),
    ]
