# Generated by Django 4.1.3 on 2022-12-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0031_alter_cast_endoperatorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="deploymenttypeid",
            field=models.ForeignKey(
                db_column="DeploymentTypeId",
                limit_choices_to={"status": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.deploymenttype",
                verbose_name="Deployment type",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="startoperatorid",
            field=models.ForeignKey(
                db_column="StartOperatorId",
                limit_choices_to={"status": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="startoperatorid",
                to="wwdb.winchoperator",
                verbose_name="Start operator",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="winchid",
            field=models.ForeignKey(
                db_column="WinchId",
                limit_choices_to={"status": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.winch",
                verbose_name="Winch",
            ),
        ),
    ]
