# Generated by Django 4.1.3 on 2022-12-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0033_winch_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winch",
            name="active",
        ),
    ]
