# Generated by Django 4.1.3 on 2022-12-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0034_remove_winch_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="payoutmaxtension",
            field=models.IntegerField(
                blank=True,
                db_column="PayoutMaxTension",
                null=True,
                verbose_name="Tension at max payout",
            ),
        ),
        migrations.AlterField(
            model_name="cutbackretermination",
            name="date",
            field=models.DateField(
                blank=True, db_column="Date", null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="wiredrum",
            name="date",
            field=models.DateField(
                blank=True, db_column="Date", null=True, verbose_name="Date"
            ),
        ),
    ]
