# Generated by Django 4.1.3 on 2022-12-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0035_cast_payoutmaxtension_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cutbackretermination",
            name="length",
        ),
    ]
