# Generated by Django 4.1.3 on 2022-12-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0036_remove_cutbackretermination_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutbackretermination",
            name="wireid",
            field=models.ForeignKey(
                blank=True,
                db_column="WireId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wirelengthreverse",
                to="wwdb.wire",
                verbose_name="Wire",
            ),
        ),
    ]
