# Generated by Django 4.1.3 on 2022-12-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0037_alter_cutbackretermination_wireid"),
    ]

    operations = [
        migrations.AddField(
            model_name="drum",
            name="location",
            field=models.ManyToManyField(
                related_name="active_location",
                through="wwdb.DrumLocation",
                to="wwdb.location",
                verbose_name="Location",
            ),
        ),
    ]
