# Generated by Django 4.1.3 on 2022-12-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0038_drum_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drumlocation",
            name="datetime",
        ),
    ]
