# Generated by Django 4.1.3 on 2022-12-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0041_alter_breaktest_wireid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breaktest",
            name="testdate",
        ),
        migrations.AddField(
            model_name="breaktest",
            name="date",
            field=models.DateTimeField(
                blank=True, db_column="Date", null=True, verbose_name="Date"
            ),
        ),
    ]
