# Generated by Django 4.1.3 on 2022-12-31 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0042_remove_breaktest_testdate_breaktest_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaktest",
            name="wireid",
            field=models.ForeignKey(
                blank=True,
                db_column="WireId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wire_break_test",
                to="wwdb.wire",
                verbose_name="Wire",
            ),
        ),
    ]
