# Generated by Django 4.1.3 on 2023-01-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0043_alter_breaktest_wireid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wire",
            old_name="winchid",
            new_name="winch",
        ),
        migrations.RenameField(
            model_name="wire",
            old_name="wireropeid",
            new_name="wirerope",
        ),
    ]
