# Generated by Django 4.1.3 on 2023-01-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0044_rename_winchid_wire_winch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wiredrum",
            old_name="wireid",
            new_name="wire",
        ),
        migrations.RemoveField(
            model_name="wiredrum",
            name="drumid",
        ),
        migrations.AddField(
            model_name="wiredrum",
            name="drum",
            field=models.ForeignKey(
                blank=True,
                db_column="DrumId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reverse_drum",
                to="wwdb.drum",
                verbose_name="Drum",
            ),
        ),
    ]
