# Generated by Django 4.1.3 on 2023-01-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0045_rename_wireid_wiredrum_wire_remove_wiredrum_drumid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="breaktest",
            old_name="wireid",
            new_name="wire",
        ),
        migrations.RenameField(
            model_name="calibration",
            old_name="calibrationid",
            new_name="calibration",
        ),
        migrations.RenameField(
            model_name="calibrationmeta",
            old_name="frameid",
            new_name="frame",
        ),
        migrations.RenameField(
            model_name="calibrationmeta",
            old_name="operatorid",
            new_name="operator",
        ),
        migrations.RenameField(
            model_name="calibrationmeta",
            old_name="winchid",
            new_name="winch",
        ),
        migrations.RenameField(
            model_name="calibrationmeta",
            old_name="wireid",
            new_name="wire",
        ),
    ]
