# Generated by Django 4.1.3 on 2023-01-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0046_rename_wireid_breaktest_wire_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cast",
            old_name="deploymenttypeid",
            new_name="deploymenttype",
        ),
        migrations.RenameField(
            model_name="cast",
            old_name="endoperatorid",
            new_name="endoperator",
        ),
        migrations.RenameField(
            model_name="cast",
            old_name="startoperatorid",
            new_name="startoperator",
        ),
        migrations.RenameField(
            model_name="cast",
            old_name="winchid",
            new_name="winch",
        ),
        migrations.RenameField(
            model_name="cast",
            old_name="wireid",
            new_name="wire",
        ),
        migrations.RenameField(
            model_name="cutbackretermination",
            old_name="wireid",
            new_name="wire",
        ),
        migrations.RenameField(
            model_name="drumlocation",
            old_name="locationid",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="drumlocation",
            old_name="winchid",
            new_name="winch",
        ),
        migrations.RenameField(
            model_name="lubrication",
            old_name="wireid",
            new_name="wire",
        ),
    ]
