# Generated by Django 4.1.3 on 2023-01-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0047_rename_deploymenttypeid_cast_deploymenttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wire",
            name="length",
        ),
        migrations.AddField(
            model_name="wire",
            name="dryendtag",
            field=models.IntegerField(
                blank=True,
                db_column="DryEndTag",
                null=True,
                verbose_name="Dry end tag value (m)",
            ),
        ),
    ]
