# Generated by Django 4.1.3 on 2023-01-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0048_remove_wire_length_wire_dryendtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cruise",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "number",
                    models.TextField(
                        blank=True,
                        db_column="Number",
                        null=True,
                        verbose_name="Cruise number",
                    ),
                ),
                (
                    "startdate",
                    models.DateField(
                        blank=True,
                        db_column="StartDate",
                        null=True,
                        verbose_name="Start date",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cruise",
                "db_table": "Cruise",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="cutbackretermination",
            name="dryendtag",
        ),
        migrations.AddField(
            model_name="cast",
            name="cruisenumber",
            field=models.ForeignKey(
                db_column="CruiseNumber",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.cruise",
                verbose_name="Cruise number",
            ),
        ),
    ]
