# Generated by Django 4.1.3 on 2023-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0049_cruise_remove_cutbackretermination_dryendtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruise",
            name="status",
            field=models.BooleanField(
                blank=True, db_column="Status", null=True, verbose_name="Status"
            ),
        ),
    ]
