# Generated by Django 4.1.3 on 2023-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0050_cruise_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="cruisenumber",
            field=models.TextField(
                db_column="CruiseNumber", null=True, verbose_name="Cruise number"
            ),
        ),
    ]
