# Generated by Django 4.1.3 on 2023-01-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0052_alter_cast_cruisenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cast",
            name="factorofsafety",
        ),
        migrations.AlterField(
            model_name="wire",
            name="winch",
            field=models.ForeignKey(
                blank=True,
                db_column="WinchId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reverse_wire",
                to="wwdb.winch",
                verbose_name="Winch",
            ),
        ),
    ]
