# Generated by Django 4.1.3 on 2023-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0053_remove_cast_factorofsafety_alter_wire_winch"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="metermaxtension",
            field=models.IntegerField(
                blank=True,
                db_column="MeterMaxTension",
                null=True,
                verbose_name="Meter mark at max tension",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="payoutmaxtension",
            field=models.IntegerField(
                blank=True,
                db_column="PayoutMaxTension",
                null=True,
                verbose_name="Payout at max tension",
            ),
        ),
    ]
