# Generated by Django 4.1.3 on 2023-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0054_cast_metermaxtension_alter_cast_payoutmaxtension"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="timemaxtension",
            field=models.DateTimeField(
                blank=True,
                db_column="TimeMaxTension",
                null=True,
                verbose_name="Time at max tension",
            ),
        ),
    ]
