# Generated by Django 4.1.3 on 2023-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0055_cast_timemaxtension"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="dryendtag",
            field=models.IntegerField(
                blank=True, db_column="DryEndTag", null=True, verbose_name="Dry end tag"
            ),
        ),
        migrations.AddField(
            model_name="cast",
            name="wetendtag",
            field=models.IntegerField(
                blank=True, db_column="WetEndTag", null=True, verbose_name="Wet end tag"
            ),
        ),
    ]
