# Generated by Django 4.1.3 on 2023-03-05 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0056_cast_dryendtag_cast_wetendtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="startdate",
            field=models.DateTimeField(
                db_column="StartDate",
                default=django.utils.timezone.now,
                verbose_name="Start date and time",
            ),
            preserve_default=False,
        ),
    ]
