# Generated by Django 4.1.3 on 2023-03-05 21:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0058_alter_cast_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="startdate",
            field=models.DateTimeField(
                db_column="StartDate",
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime.today
                    )
                ],
                verbose_name="Start date and time",
            ),
        ),
    ]
