# Generated by Django 4.1.3 on 2023-03-06 16:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0060_alter_breaktest_date_alter_calibrationmeta_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="enddate",
            field=models.DateTimeField(
                blank=True,
                db_column="EndDate",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime.today
                    )
                ],
                verbose_name="End date and time",
            ),
        ),
    ]
