# Generated by Django 4.1.3 on 2023-03-07 16:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0061_alter_cast_enddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaktest",
            name="date",
            field=models.DateField(
                blank=True,
                db_column="Date",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="Date",
            ),
        ),
    ]
