# Generated by Django 4.1.3 on 2023-03-07 16:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0062_alter_breaktest_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breaktest",
            name="date",
            field=models.DateTimeField(
                blank=True,
                db_column="Date",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime.today
                    )
                ],
                verbose_name="Date",
            ),
        ),
    ]
