# Generated by Django 4.1.3 on 2023-03-22 20:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0064_alter_breaktest_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruise",
            name="enddate",
            field=models.DateField(
                blank=True,
                db_column="EndDate",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="End date",
            ),
        ),
    ]
