# Generated by Django 4.1.3 on 2023-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0065_remove_cast_cruisenumber_cruise_enddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cruise",
            name="enddate",
            field=models.DateField(
                blank=True, db_column="EndDate", null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="cruise",
            name="startdate",
            field=models.DateField(
                blank=True, db_column="StartDate", null=True, verbose_name="Start date"
            ),
        ),
    ]
