# Generated by Django 4.1.3 on 2023-03-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0065_cruise_enddate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cast",
            name="cruisenumber",
        ),
    ]
