# Generated by Django 4.1 on 2023-09-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0066_alter_cruise_enddate_alter_cruise_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipStatus',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, db_column='Status', null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'OwnershipStatus',
                'db_table': 'OwnershipStatus',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='wire',
            name='ownershipstatus',
            field=models.ForeignKey(blank=True, db_column='OwnershipStatusId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.ownershipstatus', verbose_name='Ownership status'),
        ),
    ]
