# Generated by Django 4.1 on 2023-10-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0067_ownershipstatus_wire_ownershipstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, db_column='Number', null=True, verbose_name='Number')),
            ],
            options={
                'verbose_name_plural': 'Motor',
                'db_table': 'Motor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cast',
            name='motor',
            field=models.ForeignKey(blank=True, db_column='MotorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wwdb.motor', verbose_name='Motor'),
        ),
    ]
