# Generated by Django 4.1 on 2023-11-27 17:14

from django.db import migrations, models
import wwdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0068_motor_cast_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='scienceprovidedwinch',
            field=models.TextField(blank=True, db_column='ScienceProvidedWinch', null=True, validators=[wwdb.models.validate_commas], verbose_name='Science Provided Winch'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch1',
            field=models.BooleanField(blank=True, db_column='Winch1', null=True, verbose_name='Winch 1'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch1blockarrangement',
            field=models.TextField(blank=True, db_column='Winch1BlockArrangement', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 1 Block Arrangement'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch1notes',
            field=models.TextField(blank=True, db_column='Winch1Notes', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 1 Notes'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch1termination',
            field=models.TextField(blank=True, db_column='Winch1Termination', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 1 Termination'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch2',
            field=models.BooleanField(blank=True, db_column='Winch2', null=True, verbose_name='Winch 2'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch2blockarrangement',
            field=models.TextField(blank=True, db_column='Winch2BlockArrangement', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 2 Block Arrangement'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch2notes',
            field=models.TextField(blank=True, db_column='Winch2Notes', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 2 Notes'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch2spindirection',
            field=models.TextField(blank=True, db_column='Winch2SpinDirection', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 3 Spin Direction'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch2termination',
            field=models.TextField(blank=True, db_column='Winch2Termination', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 2 Termination'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch3',
            field=models.BooleanField(blank=True, db_column='Winch3', null=True, verbose_name='Winch 3'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch3blockarrangement',
            field=models.TextField(blank=True, db_column='Winch3BlockArrangement', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 3 Block Arrangement'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch3notes',
            field=models.TextField(blank=True, db_column='Winch3Notes', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 3 Notes'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='winch3termination',
            field=models.TextField(blank=True, db_column='Winch3Termination', null=True, validators=[wwdb.models.validate_commas], verbose_name='Winch 3 Termination'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='number',
            field=models.TextField(blank=True, db_column='Number', null=True, validators=[wwdb.models.validate_commas], verbose_name='Cruise number'),
        ),
    ]
