# Generated by Django 4.1 on 2023-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0069_cruise_scienceprovidedwinch_cruise_winch1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutbackretermination',
            name='lengthaftercutback',
            field=models.IntegerField(blank=True, db_column='LengthAfterCutback', null=True, verbose_name='Length after cutback'),
        ),
    ]
