# Generated by Django 4.1 on 2023-12-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwdb', '0070_cutbackretermination_lengthaftercutback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutbackretermination',
            name='lengthremoved',
        ),
    ]
