# Generated by Django 4.1.3 on 2023-12-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0071_remove_cutbackretermination_lengthremoved"),
    ]

    operations = [
        migrations.AddField(
            model_name="drumlocation",
            name="wire",
            field=models.ForeignKey(
                blank=True,
                db_column="WireId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.wire",
                verbose_name="Wire",
            ),
        ),
    ]
