# Generated by Django 4.1.3 on 2023-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0072_drumlocation_wire"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutbackretermination",
            name="dryendtag",
            field=models.IntegerField(
                blank=True,
                db_column="DryEndTag",
                null=True,
                verbose_name="Dry end tag value (m)",
            ),
        ),
    ]
