# Generated by Django 4.1.3 on 2024-02-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0073_cutbackretermination_dryendtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="deploymenttype",
            field=models.ForeignKey(
                db_column="DeploymentTypeId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.deploymenttype",
                verbose_name="Deployment type",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="endoperator",
            field=models.ForeignKey(
                db_column="EndOperatorId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="endoperatorid",
                to="wwdb.winchoperator",
                verbose_name="End operator",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="startoperator",
            field=models.ForeignKey(
                db_column="StartOperatorId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="startoperatorid",
                to="wwdb.winchoperator",
                verbose_name="Start operator",
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="winch",
            field=models.ForeignKey(
                db_column="WinchId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.winch",
                verbose_name="Winch",
            ),
        ),
    ]
