# Generated by Django 4.1.3 on 2024-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0074_alter_cast_deploymenttype_alter_cast_endoperator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deploymenttype",
            options={
                "managed": True,
                "ordering": ["name"],
                "verbose_name_plural": "DeploymentType",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "managed": True,
                "ordering": ["location"],
                "verbose_name_plural": "Location",
            },
        ),
        migrations.AlterModelOptions(
            name="winch",
            options={
                "managed": True,
                "ordering": ["name"],
                "verbose_name_plural": "Winch",
            },
        ),
        migrations.AlterModelOptions(
            name="winchoperator",
            options={
                "managed": True,
                "ordering": ["username"],
                "verbose_name_plural": "WinchOperator",
            },
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch1",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch2",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch3",
        ),
        migrations.AddField(
            model_name="lubrication",
            name="lubeendmetermark",
            field=models.IntegerField(
                blank=True,
                db_column="LubeEndMeterMark",
                null=True,
                verbose_name="End meter mark",
            ),
        ),
        migrations.AddField(
            model_name="lubrication",
            name="lubestartmetermark",
            field=models.IntegerField(
                blank=True,
                db_column="LubeStartMeterMark",
                null=True,
                verbose_name="Start meter mark",
            ),
        ),
    ]
