# Generated by Django 4.1.3 on 2024-04-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0075_alter_deploymenttype_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cruise",
            name="status",
        ),
        migrations.AddField(
            model_name="cruise",
            name="winch1status",
            field=models.BooleanField(
                blank=True,
                db_column="Winch1Status",
                null=True,
                verbose_name="Winch 1 status",
            ),
        ),
        migrations.AddField(
            model_name="cruise",
            name="winch2status",
            field=models.BooleanField(
                blank=True,
                db_column="Winch2Status",
                null=True,
                verbose_name="Winch 2 status",
            ),
        ),
        migrations.AddField(
            model_name="cruise",
            name="winch3status",
            field=models.BooleanField(
                blank=True,
                db_column="Winch3Status",
                null=True,
                verbose_name="Winch 3 status",
            ),
        ),
    ]
