# Generated by Django 4.1.3 on 2024-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0075_terminationtype_alter_deploymenttype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminationtype",
            name="name",
            field=models.TextField(
                blank=True, db_column="Name", verbose_name="Termination Type"
            ),
        ),
    ]
