# Generated by Django 4.1.3 on 2024-07-30 06:34

from django.db import migrations, models
import wwdb.models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0076_remove_cruise_status_cast_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruise",
            name="statuss",
            field=models.BooleanField(
                blank=True,
                db_column="Status",
                null=True,
                validators=[wwdb.models.validate_commas],
                verbose_name="status",
            ),
        ),
    ]
