# Generated by Django 4.1.3 on 2024-03-07 11:02

from django.db import migrations, models
import wwdb.models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0076_alter_terminationtype_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cruise",
            old_name="scienceprovidedwinch",
            new_name="scienceprovidedwinchnotes",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch1blockarrangement",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch1notes",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch1termination",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch2blockarrangement",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch2notes",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch2spindirection",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch2termination",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch3blockarrangement",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch3notes",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="winch3termination",
        ),
        migrations.AddField(
            model_name="cruise",
            name="winchnotes",
            field=models.TextField(
                blank=True,
                db_column="WinchNotes",
                null=True,
                validators=[wwdb.models.validate_commas],
                verbose_name="Winch Notes",
            ),
        ),
    ]
