# Generated by Django 4.1.3 on 2024-07-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0077_cruise_statuss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cruise",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cruise",
            name="statuss",
        ),
    ]
