# Generated by Django 4.1.3 on 2024-03-22 06:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "wwdb",
            "0077_rename_scienceprovidedwinch_cruise_scienceprovidedwinchnotes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WireLocation",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        db_column="Date",
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="Notes", null=True, verbose_name="notes"
                    ),
                ),
                (
                    "enteredby",
                    models.ForeignKey(
                        blank=True,
                        db_column="EnteredBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entered by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="LocationId",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wwdb.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WireLocation",
                "db_table": "WireLocation",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="drumlocation",
            name="drumid",
        ),
        migrations.RemoveField(
            model_name="drumlocation",
            name="enteredby",
        ),
        migrations.RemoveField(
            model_name="drumlocation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="drumlocation",
            name="winch",
        ),
        migrations.RemoveField(
            model_name="drumlocation",
            name="wire",
        ),
        migrations.RemoveField(
            model_name="wiredrum",
            name="drum",
        ),
        migrations.RemoveField(
            model_name="wiredrum",
            name="wire",
        ),
        migrations.RemoveField(
            model_name="cast",
            name="motor",
        ),
        migrations.RemoveField(
            model_name="winch",
            name="drums",
        ),
        migrations.RemoveField(
            model_name="winch",
            name="wiretrainschematicaframe",
        ),
        migrations.RemoveField(
            model_name="winch",
            name="wiretrainschematicjframe",
        ),
        migrations.RemoveField(
            model_name="wire",
            name="drums",
        ),
        migrations.DeleteModel(
            name="Drum",
        ),
        migrations.DeleteModel(
            name="DrumLocation",
        ),
        migrations.DeleteModel(
            name="Motor",
        ),
        migrations.DeleteModel(
            name="Wiredrum",
        ),
        migrations.AddField(
            model_name="wirelocation",
            name="winch",
            field=models.ForeignKey(
                blank=True,
                db_column="WinchId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.winch",
                verbose_name="Winch",
            ),
        ),
        migrations.AddField(
            model_name="wirelocation",
            name="wireid",
            field=models.ForeignKey(
                blank=True,
                db_column="WireId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.wire",
                verbose_name="Wire",
            ),
        ),
    ]
