# Generated by Django 4.1.3 on 2024-03-22 06:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0078_wirelocation_remove_drumlocation_drumid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wire",
            name="dateacquired",
            field=models.DateField(
                blank=True,
                db_column="DateAcquired",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime.today
                    )
                ],
                verbose_name="Date Acquired",
            ),
        ),
    ]
