# Generated by Django 4.1.3 on 2024-07-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0080_alter_cast_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="winch",
            field=models.ForeignKey(
                db_column="WinchId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cast_winch",
                to="wwdb.winch",
                verbose_name="Winch",
            ),
        ),
    ]
