# Generated by Django 4.1.3 on 2024-07-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0081_alter_cast_winch"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="wirelength",
            field=models.IntegerField(
                blank=True,
                db_column="WireLength",
                null=True,
                verbose_name="Wire length",
            ),
        ),
    ]
