# Generated by Django 4.1.3 on 2024-07-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0082_cast_wirelength"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="Safeworkingtension",
            field=models.FloatField(
                db_column="SafeWorkingTension",
                null=True,
                verbose_name="Safe Working tension",
            ),
        ),
        migrations.AddField(
            model_name="cast",
            name="factorofsafety",
            field=models.FloatField(
                db_column="FactorofSafety", null=True, verbose_name="Factor of safety"
            ),
        ),
    ]
