# Generated by Django 4.1.3 on 2024-07-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0083_cast_safeworkingtension_cast_factorofsafety"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cast",
            old_name="Safeworkingtension",
            new_name="safeworkingtension",
        ),
    ]
