# wwdb/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [
    path('home/', views.home, name='home'),
    path('castlist/', views.castlist, name='castlist'),
    path('cast/<int:pk>/', views.castdetail, name='castdetail'),
    path('cast/<id>/castenddetail', views.castenddetail, name='castenddetail'),
    path('cast/', views.caststart, name='caststart'),
    path('cast/<int:id>/edit/', views.castedit, name='castedit'),
    path('cast/<int:id>/delete/', CastDelete.as_view(), name='castdelete'),
    path('cast/<id>/castend/', views.castend, name='castend'),
    path('wirelist/', WireList.as_view(), name='wirelist'),
    path('wire/<int:pk>/wiredetail', WireDetail.as_view(), name='wiredetail'),
    path('wire/<int:pk>/edit/', WireEdit.as_view(), name='wireedit'),
    path('wire/<int:id>/editfactorofsafety/', views.wireeditfactorofsafety, name='wireeditfactorofsafety'),
    path('wireadd/', WireAdd.as_view(), name='wireadd'),
    path('winchlist/', WinchList.as_view(), name='winchlist'),
    path('winch/<int:pk>/winchdetail', WinchDetail.as_view(), name='winchdetail'),
    path('winch/<int:pk>/edit/', WinchEdit.as_view(), name='winchedit'),
    path('winch/<int:id>/editstatus/', views.wincheditstatus, name='wincheditstatus'),
    path('winchadd/', WinchAdd.as_view(), name='winchadd'),
    path('operatorlist/', OperatorList.as_view(), name='operatorlist'),
    path('operator/<int:pk>/operatordetail', OperatorDetail.as_view(), name='operatordetail'),
    path('operator/<int:pk>/edit/', OperatorEdit.as_view(), name='operatoredit'),
    path('operator/<int:id>/editstatus/', views.operatoreditstatus, name='operatoreditstatus'),
    path('operatoradd/', views.operatoradd, name='operatoradd'),
    path('deploymentlist/', DeploymentList.as_view(), name='deploymentlist'),
    path('deployment/<int:pk>/deploymentdetail', DeploymentDetail.as_view(), name='deploymentdetail'),
    path('deployment/<int:pk>/edit/', DeploymentEdit.as_view(), name='deploymentedit'),
    path('deployment/<int:id>/editstatus/', views.deploymenteditstatus, name='deploymenteditstatus'),
    path('deploymentadd/', views.deploymentadd, name='deploymentadd'),
    path('reports/breaktestlist/', views.breaktestlist, name='breaktestlist'),
    path('reports/cutbackreterminationlist/', views.cutbackreterminationlist, name='cutbackreterminationlist'),
    path('cutbackretermination/<int:pk>/deploymentdetail', CutbackReterminationDetail.as_view(), name='cutbackreterminationdetail'),
    path('cutbackretermination/<int:id>/edit/', views.cutbackreterminationedit, name='cutbackreterminationedit'),
    path('cutbackreterminationadd/', views.cutbackreterminationadd, name='cutbackreterminationadd'),
    path('cruiseconfigurehome/', views.cruiseconfigurehome, name='cruiseconfigurehome'),
    path('reports/reporting/', views.reportinghome, name='reporting'),
    path('reports/safeworkingtensions/', views.safeworkingtensions, name='safeworkingtensions'),
    path('reports/inventories/', views.inventories, name='inventories'),
    path('reports/wiredrumlist/', views.wiredrumlist, name='wiredrumlist'),
    path('wiredrum/<int:id>/edit/', views.wiredrumedit, name='wiredrumedit'),
    path('wiredrumadd/', views.wiredrumadd, name='wiredrumadd'),
    path('drumlocationadd/', views.drumlocationadd, name='drumlocationadd'),
    path('reports/drumlist/', views.drumlist, name='drumlist'),
    path('drum/<int:pk>/drumdetail', DrumDetail.as_view(), name='drumdetail'),
    path('drum/<int:id>/edit/', views.drumedit, name='drumedit'),
    path('drumadd/', views.drumadd, name='drumadd'),
    path('cruiseadd/', views.cruiseadd, name='cruiseadd'),
    path('cruise/<int:id>/edit/', views.cruiseedit, name='cruiseedit'),
    path('reports/cruisereport/', views.cruisereport, name='cruisereport'),
    path('highchart/', views.highchart, name='highchart'),
]